### Creating tensors like other tensors

In [1]:
import torch

In [2]:
#@title Create a tensor of shape (2, 5) filled with ones
starting_tensor = torch.zeros(2,5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
#@title Create a tensor with the same size filled with random numbers
torch.manual_seed(111)
rand_tensor=torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

In [8]:
#@title Create a tensor with the same shape filled with ones
torch.ones_like(rand_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [9]:
#@title Create a tensor with the same shape filled with provided value
torch.full_like(starting_tensor,7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])